/*
 * DIO_cnfg.c
 *
 *  Created on: ??þ/??þ/????
 *      Author: COMPUTER SHOW
 */
#include "DIO_cnfg.h"

DIO_cnfg_t DIO_cnfg_arr [NUM_OF_PINS] =
{
	{PORT_B,PIN4,OUTPUT,LOW,NA,INITIALIZED},
	{PORT_A,PIN5,OUTPUT,LOW,NA,INITIALIZED},
	{PORT_B,PIN2,OUTPUT,LOW,NA,INITIALIZED},
	{PORT_B,PIN3,OUTPUT,LOW,NA,INITIALIZED},
	{PORT_B,PIN4,OUTPUT,LOW,NA,INITIALIZED},
	{PORT_B,PIN5,OUTPUT,LOW,NA,INITIALIZED}
};

